#!/bin/bash

# Set the name of your main LaTeX file (without extension)
LATEX_FILE="main.tex"

# Compile the LaTeX file with pdflatex (or use latexmk for automatic handling of multiple passes)
pdflatex $LATEX_FILE

# Optionally run pdflatex twice to ensure proper references and table of contents
pdflatex $LATEX_FILE

# Clean up temporary files generated by LaTeX
rm -f *.aux *.log *.out *.toc *.fls *.fdb_latexmk

echo "Compilation complete and temporary files removed."

